# Generated by Django 3.2.8 on 2021-11-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinMarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
