# Generated by Django 3.2.8 on 2021-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinMarket', '0002_alter_coin_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
