# Generated by Django 3.2.8 on 2021-11-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinMarket', '0003_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='typeCoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinMarket.typecoin'),
        ),
    ]
